AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SamTemplateFunction
      Timeout: 30
      Handler: http4k.form.sam.aws.App::handle
      Runtime: java8
      CodeUri: ../../../build/libs/http4k-form-sam-aws-all.jar
      Policies:
        - AWSLambdaExecute
